<form action="/article/save" method="post">
<h2 class="article_title"><input type="text" name="title" value="<?php echo $this->title ?>"/></h2>
<div class="article_body">
    <textarea name="body" value=""><?php echo $this->body ?></textarea>
</div>
    <input name="return" type="hidden" value="<?php echo $this->return ?>">
    <input name="id" type="hidden" value="<?php echo $this->article_id ?>">
    <input name="submit" type="submit" value="Submit">
</form>