<!DOCTYPE html>
<html>
<head>
    <script src="script/script.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="style/style.css">
    <title>microCMS site</title>
</head>
<body>
<div class="main">
    <div class="header">
        <div class="col left_col"></div>
        <div class="menu">
            <h1>microCMS site v1.0</h1>
            <nav>
                <ul>
                    <li><a href="#">Article 1</a></li>
                    <li><a href="#">Article 2</a>
                        <ul>
                            <li><a href="#">Article 2.1</a></li>
                            <li><a href="#">Article 2.2</a>
                                <ul>
                                    <li><a href="#">Article 2.2.1</a></li>
                                    <li><a href="#">Article 2.2.2</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Article 2.3</a>
                                <ul>
                                    <li><a href="#">Article 2.3.1</a></li>
                                    <li><a href="#">Article 2.3.2</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="login">
            <form action="login" method="post">
                <label>Login:</label><br/>
                <input  type="text" placeholder="Please enter login"/><br/>
                <label>Password:</label><br/>
                <input type="password" placeholder="Please  enter pass"/><br/>
                <input type="submit" value="Submit">
            </form>

        </div>

    </div>
    <div class="wrap">
        <div class="col left_col">

        </div>
        <div class="col content">
            <h2 class="article_title">Lorem ipsum dolor sit amet</h2>
            <div class="article_body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec porta lacus, id vehicula ligula. Nam egestas ultrices orci vitae lacinia. Maecenas at elementum orci, vitae pulvinar magna. Phasellus ut arcu tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc tempus neque nec elit cursus, eu egestas lacus placerat. Cras placerat malesuada velit id fringilla. Proin commodo at nisi in tempor. Sed et ligula eget est hendrerit ultrices sed vitae purus. Etiam condimentum ante ac erat faucibus, non tincidunt dolor posuere. Duis pulvinar nisl vel erat tincidunt, sit amet pulvinar ligula rutrum. Proin tristique nulla non molestie adipiscing.
                Aenean ac placerat felis, eget vulputate ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam mattis ultrices elit, auctor cursus nisl semper sit amet. Fusce egestas fermentum est, in ornare dolor vestibulum tempus. Morbi pellentesque quam sapien, sit amet elementum turpis semper eget. Ut mollis nunc ut nulla convallis pulvinar. Duis id odio rutrum, eleifend magna vitae, commodo lorem. Donec eget felis aliquet turpis tempus varius eget cursus quam.
                Quisque quis posuere nisi. Morbi adipiscing leo lacus, quis mollis ligula aliquam sed. Integer sed purus erat. Duis at arcu et magna rutrum feugiat. Nulla tincidunt varius lacus nec convallis. Nullam sagittis ultrices mattis. Nullam ipsum ante, auctor a blandit in, laoreet at ligula. Nulla in metus id lacus adipiscing sodales non et mi. Fusce neque tellus, varius a placerat a, lobortis in eros. Curabitur interdum lorem odio, vitae vulputate nibh pharetra non. Phasellus non turpis risus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam at molestie ipsum. Phasellus semper, orci sollicitudin blandit dignissim, erat eros aliquet nibh, sit amet adipiscing libero elit rhoncus neque. Etiam elementum at erat in scelerisque. Morbi venenatis velit non orci laoreet, id hendrerit enim tempor.
                Sed quis scelerisque urna. Nullam elementum iaculis sapien at accumsan. Phasellus laoreet libero sit amet tellus posuere, non gravida nibh tincidunt. Maecenas et nisl ac augue cursus posuere interdum at odio. Donec aliquet leo nec purus hendrerit, sit amet molestie tellus sodales. Nam porttitor dignissim eros, sed iaculis enim facilisis eget. Praesent rhoncus magna nibh, eu convallis ipsum consequat in. Nunc sagittis dolor quis nulla ullamcorper, eu ornare odio aliquet. Mauris hendrerit est odio, vitae vehicula sapien lacinia quis. Praesent volutpat ultricies arcu, ac consectetur orci. Nulla porta purus at sem ullamcorper, ac placerat nibh consequat. Etiam vehicula, eros eu scelerisque pellentesque, purus lorem adipiscing nisl, vitae vehicula neque lectus in eros. Ut iaculis quam nisl, non fermentum nulla porttitor vitae. Nam libero lorem, iaculis quis semper quis, pellentesque a lorem. Phasellus vestibulum convallis ultrices.
                Proin enim enim, blandit vel orci sed, vehicula feugiat arcu. Sed in sem enim. Curabitur vel purus consequat odio consequat condimentum. Donec neque leo, vestibulum id ullamcorper ut, gravida sit amet sapien. Quisque eu pellentesque nulla. Ut ut sodales felis. Fusce laoreet, nibh in pulvinar pretium, magna risus consectetur ipsum, eu faucibus est dui non nisl. Vivamus eget lacinia est. Morbi suscipit semper purus at interdum.
            </div>
        </div>
        <div class="col right_col">

        </div>
    </div>
    <div class="footer">
        Copyright 2014 microCMS ;)
    </div>
</div>
</body>
</html>