<!DOCTYPE html>
<html>
<head>
    <script src="script/script.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="style/style.css">
    <title>microCMS site</title>
</head>
<body>
<div class="main">
    <div class="header">
        <div class="col left_col"></div>
        <div class="menu">
            <h1>microCMS site v1.0</h1>
            <nav>
                <ul>
                    <li><a href="#">Article 1</a></li>
                    <li><a href="#">Article 2</a>
                        <ul>
                            <li><a href="#">Article 2.1</a></li>
                            <li><a href="#">Article 2.2</a>
                                <ul>
                                    <li><a href="#">Article 2.2.1</a></li>
                                    <li><a href="#">Article 2.2.2</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Article 2.3</a>
                                <ul>
                                    <li><a href="#">Article 2.3.1</a></li>
                                    <li><a href="#">Article 2.3.2</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="login">
            <form action="login" method="post">
                <label>Login:</label><br/>
                <input  type="text" placeholder="Please enter login"/><br/>
                <label>Password:</label><br/>
                <input type="password" placeholder="Please  enter pass"/><br/>
                <input type="submit" value="Submit">
            </form>

        </div>

    </div>
    <div class="wrap">
        <div class="col left_col">

        </div>
        <div class="col content">
            <?php echo $this->content ?>
        </div>
        <div class="col right_col">

        </div>
    </div>
    <div class="footer">
        Copyright 2014 microCMS ;)
    </div>
</div>
</body>
</html>