<!DOCTYPE html>
<html>
<head>
    <script src="/script/script.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="/style/style.css">
    <title>microCMS site</title>
</head>
<body>
<div class="main">
    <div class="header">
        <div class="col left_col"></div>
        <div class="menu">
            <h1>microCMS site v1.0</h1>
            <?php echo $this->menu ?>
        </div>
        <div class="login">
            <?php echo $this->login ?>
        </div>

    </div>
    <div class="wrap">
        <div class="col left_col">

        </div>
        <div class="col content">
            <?php echo $this->content ?>
        </div>
        <div class="col right_col">

        </div>
    </div>
    <div class="footer">
        Copyright 2014 microCMS ;)
    </div>
</div>
</body>
</html>